from Arvore import *
teste = BinarySearchTree()
teste.insert("Davi")
teste.insert("Bia")
teste.insert("Andre")
teste.insert("Carlos")
print("\n")
teste.postorder_traversal()
teste.inorder_traversal()
#TEM QUE TESTAR DEPOIS// teste.levelorder_traversal()
print(teste.height())
print(teste.search("Davi"))
print(teste.min())
print(teste.max())
teste.levelorder_traversal()
print(teste.size())
print(teste.preorder())
print(teste.internal_path_length())
